{
    "name": "Laundry Management",
    "version": "1.0",
    "summary": "Modul manajemen laundry untuk Odoo",
    "description": "Modul ini memungkinkan Anda mengelola pesanan laundry, pelanggan, layanan, dan karyawan.",
    "author": "Ariya Pratama Adjie Nugroho",
    "website": "https://www.laundrysigap.com",
    "category": "Services",
    "depends": ["base", "mail", "hr"],
    "data": [
        "security/ir.model.access.csv",
        'security/laundry_groups.xml',
        "security/security.xml",
        "views/laundry_order_views.xml",
        "views/laundry_order_line_views.xml",
        'views/laundry_product_views.xml',
        "views/laundry_customer_views.xml",
        "views/laundry_employee_views.xml",
        "views/laundry_service_views.xml",
        "data/demo_data.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
